### ISSUE TITLE
Black and white spectrograms

### ISSUE THREAD

**Issue by Vollpflock** [Mattk70/Chirpity-Electron#103]
**Is your feature request related to a problem? Please describe.**
Sometimes I have difficulties to quickly read the spectrogram and need to listen in.

**Describe the solution you'd like**
Spectrograms in black and white with higher contrast, similar to those on Xeno-Canto, would be easier to read.

**Describe alternatives you've considered**
none

**Additional context**
Again, very minor and probably complicated to implement.

**Comment by Mattk70** [comment]
Have you tried the 'greyscale' or 'bone' colormaps? These are essentially greyscale. I did look into a contrast adjustment a while back, and put that idea on the shelf, as there were more important things to fix!

**Comment by Vollpflock** [comment]
Thank you. Yeah but it's not really comparable to a contrasty black-and-white like XC has.

**Comment by Mattk70** [comment]
I should also mention, because it seems absolutely no-one but me uses this feature, that you can adjust the fft window size of the spectrogram by holding shift while pressing plus or minus. I find this essential to view the clearest spectrogram image as I zoom in and out of a view of a call.

Here's an example:
![image](https://github.com/Mattk70/Chirpity-Electron/assets/61826357/1d361469-71d9-4913-a286-073bac8ccdf3)


Zoomed in:
![image](https://github.com/Mattk70/Chirpity-Electron/assets/61826357/d0788c83-ba58-4ccf-aabe-5d4f9b4456e8)

Hold shift and plus, and the details of the modulations become clearer:
![image](https://github.com/Mattk70/Chirpity-Electron/assets/61826357/e71a5ca1-513b-478b-96e0-e7acb6d4252b)

**Comment by Vollpflock** [comment]
Don't worry, I'm aware :)

**Comment by Vollpflock** [comment]
> I should also mention, because it seems absolutely no-one but me uses this feature, that you can adjust the fft window size of the spectrogram by holding shift while pressing plus or minus. I find this essential to view the clearest spectrogram image as I zoom in and out of a view of a call.

Could you quickly tell me what this is for mac? Can't find a way to zoom in and out.

**Comment by Mattk70** [comment]
If you just want to zoom in / out, you can use either of the magnifying glasses on the transport bar. Alternatively, press + or - (actually minus or equals keys) on the keyboard. If you hold shift while doing that, it will change the FFT window size. You can't zoom out to a level that would prevent the spectrogram filling the screen.

**Comment by Vollpflock** [comment]
Yeah, but what are the keyboard shortcuts for mac to zoom in / out? I can't find them

**Comment by Vollpflock** [comment]
Thank you. Oh wow, that's on the " ' " and "^" on a Swiss keyboard layout.

**Comment by Mattk70** [comment]
Oh really!? Could you do a test for me? On this site: https://keyjs.dev/ press your + and - keys. Let me know what the value for e.code and e.key is?

**Comment by Vollpflock** [comment]
+: 
e.key: 1
e.code: Digit1


-:
e.key: -
e.code: Slash

**Comment by Mattk70** [comment]
Black and White spectrograms are possible by creating a custom colormap in 1.8.0

The keys mapping issue is not straghtforward: there's no simple way to establish how the keyboard is laid out. There may be a library I can use, I'll look into it.

**Comment by Vollpflock** [comment]
No worries, it's not that important.
