### ISSUE TITLE
Analyzing all files at once from different locations

### ISSUE THREAD

**Issue by Vollpflock** [Mattk70/Chirpity-Electron#108]
**Is your feature request related to a problem? Please describe.**
I have multiple recording stations running simultaneously at different locations and want to analyze them at once (over night).

**Describe the solution you'd like**
Analyzing all files from different locations at once. That means "Amend file recording location" with one location for certain files and with another location for other files.

**Describe alternatives you've considered**
Analyzing location by location.
Or analyzing in multiple windows. This doesn't work, however.

**Comment by Mattk70** [comment]
I haven't tried this, but are you sure using multiple windows doesn't work? What happens? I know when you set a file location you have to do it either for one file or all of them, but if you did open multiple windows, and opened the files from specific locations in each window, I would expect this to work.

**Comment by Vollpflock** [comment]
I need to re-test this. Tested it a month ago. I analyzed files in 2 windows and got strange results in one window.

**Comment by Vollpflock** [comment]
I got this error message when testing.
![Screenshot 2024-04-18 at 21 07 19](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/ad1e664c-15c4-4ba8-aa3f-aff3b61e8459)

**Comment by Mattk70** [comment]
Were you analysing compressed files in the window with the errors? i.e. not WAV files...

The error you are seeing is triggered within fluent-ffmpeg, but may be caused by the way Node.js handles streams.  What seems to be happening is that the output stream is closed by node before the sub-process spawned for ffmpeg has managed to close. I _think_ this only happens _after_ the last segment of the file has been read and processed, in which case, although the error cannot be trapped, it can be ignored.

I have made some changes to the fluent-ffmpeg code in Chirpity 1.7.2. fluent-ffmpeg has a timeout to protect against this issue, I increased it, which should help.

**Comment by Vollpflock** [comment]
Thank you. You're right, it seems to be working now. Yep, just m4a from now on. Uses a fraction of storage and pretty much the same quality imv.

**Comment by Mattk70** [comment]
I'm not sure if I can do anything more to fix this. There's a WASM version of ffmpeg, which would run in-process and presumably prevent this ffmpeg error, but it's slower (that might not be an issue, it still may not be a bottleneck), and secondly the WASM version is limited to a maximum 2GB file size, which would be a bigger issue, I think.

I *guess* the old way would also avoid this problem. Before v1.4.0, any compressed file was first converted to wav (if you remember, this was the "extracting file" stage) and that wav was cached as a temporary file. However, the cache needed to be HUGE and it was a very poor experience when browsing the archive.

If you were analysing wav's, you would avoid ffmpeg during analysis altogether.

Anyway, I don't think the issue here is because you have two windows open doing analysis. It's to do with the streaming conversion of the compressed files, perhaps stressed by the multiple windows putting the processes under extreme load.

It's possible that the counter-intuitive step of increasing the batch size may help. I would also try adjusting the threads count such that the total number of threads for all windows didn't exceed the number of cores on the machine. E.G suppose you have an 8 core CPU: using 2 windows - set threads to 4.

**Comment by Mattk70** [comment]
I just ran a test on my PC, running all cores/threads in both windows for 20 3-hour files in each window. It ran out of memory. Reducing the threads (4 in each window - my PC has 8 P-cores) seems to work. Slower, but error-free.

**Comment by Vollpflock** [comment]
In my case, it was only using 2* 300 % CPU (10-core M1 Mac, 7 threads, 16 batch size). Yes, I could try reducing threads. But actually, I think it's easier to create a separate folder for each recording location, analyze all files from all locations at once and amend file recording location in retrospect.

**Comment by Mattk70** [comment]
Can you try this again  with 1.8.0?

**Comment by Vollpflock** [comment]
Nope, it got stuck again. Seems to be the same issue as https://github.com/Mattk70/Chirpity-Electron/issues/120. However, as already mentioned, I think it's easier to create a separate folder for each recording location, analyze all files from all locations at once and amend file recording location in retrospect. So I don't care if it's not working.

![Screenshot 2024-04-24 at 20 43 40](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/d9021b8c-da64-4e05-8c82-6984470911b9)
![Screenshot 2024-04-24 at 20 44 21](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/3e3b2655-89c1-4980-9baa-2a7276491be4)

**Comment by Mattk70** [comment]
Was this 1.8.0 or 1.8.1?

**Comment by Vollpflock** [comment]
1.8.0, will try again with 1.8.1

**Comment by Vollpflock** [comment]
Seems to work now 👍
