### ISSUE TITLE
Keyboard shortcut for "Edit Record"

### ISSUE THREAD

**Issue by Vollpflock** [Mattk70/Chirpity-Electron#109]
**Is your feature request related to a problem? Please describe.**
I go through hundreds of detections for reporting. For every certain individual, I right-click on the detection, click on "Edit Record" and hit "save". I then export it as a CSV, run a script that cuts out all rows except the "certain" ones and sets individuals counted to 1 everywhere where it's not specified. 

**Describe the solution you'd like**
Keyboard shortcut for "Edit Record".

**Describe alternatives you've considered**
Continuing as before.

**Additional context**
Very minor issue. However, it's still annoying to right click thousands of times.

This has somewhat already been discussed under https://github.com/Mattk70/Chirpity-Electron/discussions/61 (separating “Share online” and “Just keep them for my own use” more?).

**Comment by Mattk70** [comment]
So, rather than an "Edit Record" shortcut, I think you'd like a shortcut to confirm a record?

Ctrl or Option C is taken, it centres the audio at the playhead position.

Ctrl or Option V is available. That could be a shortcut to "Verify / Validate" a record.

If you wanted to add a call count, label or comment, you'd still need to right click.

**Comment by Vollpflock** [comment]
Ctrl or Option V would be great!
