### ISSUE TITLE
Different Time in Detection List and Timeline

### ISSUE THREAD

**Issue by FlorianH27** [Mattk70/Chirpity-Electron#150]
**Describe the bug**
After changing the Start Time of a File manually, Chirpity sometimes struggles with displaying the correct time. The time in the detection list is sometimes 1 hour behind the time in the timeline. In some cases it corrects itself after clicking on another record and coming back to the initial one. But this doesn't work always.

**Screenshots**
![image](https://github.com/user-attachments/assets/a28b188c-125d-4220-8b97-80a0b1d2e494)

**Comment by Mattk70** [comment]
@FlorianH27 , thanks for letting me know!

I have got to the bottom of what is going on. It's a dooozy! If you alter the file's start time after analysing results, you occasionally run into an issue where the new time for a species detection contains an identical record for that species at the original start time. Since the program won't allow duplicate records for a species at the same time and location there's an error, and the records update fails.

I have fixed this now, it took a little while. Whilst looking into that, I realised there is another bug, which is that the records are saved with a flag to say whether that record was picked up during the daytime or the night time. When the records are updated, the flag is not changed. So, if your file spans day and night time, whilst the record is updated to the new time, the flag will not change. 

That means records that should be daytime records with the new time are still showing as night time ones (and also a daytime record may now be a night time one - you'd have the same issue).

All in all this is fixed - and I'll add that fix to the next release. 

However - **it really is best to amend files' start times before analysis** *especially* if you have nocmig mode on - as you do in your screenshot. When using nocmig mode, Chirpity skips the analysis of daytime periods entirely. If after the analysis you change the file start time, it will update the records it has, but only for the period of night associated with the original start time

**Comment by FlorianH27** [comment]
Thank you very much for your prompt reply and your efforts!

**Comment by FlorianH27** [comment]
![image](https://github.com/user-attachments/assets/c4f5f793-0887-4d8d-93c3-5dc431253cf5)
I still have problems with the displayed timecode, even in cases i didn't change anything in the starting time of my file.

**Comment by Mattk70** [comment]
Could you try installing the latest version after downloading the installer from the website? 

Since the timeline and results are configured to show the position in the file, I’m sure this isn’t a time zone issue but it beats me why you’d have a discrepancy! The reason I’m suggesting a download from the website is that it will ensure you have installed a fresh copy rather than a patch. Database and settings will be preserved. Let me know if this resolves things?

**Comment by FlorianH27** [comment]
I already get the bug after this basic steps:
- Open a File 
- Analyse
![image](https://github.com/user-attachments/assets/0a6eb7d4-be8f-45a6-8a14-1e08639776dd)

**Comment by FlorianH27** [comment]
With time of the day everything seems to work in this file:
![image](https://github.com/user-attachments/assets/aa03d042-ece2-41df-a3a5-a62435d320b6)

**Comment by Mattk70** [comment]
Aha. I've been using Date.UTC to set midnight, or a starting position of 00:00:00.000, so it *is* affected by timezone. I've fixed it now, ready for the next release. Thanks for letting me now !
