### ISSUE TITLE
Jumping on timeline when applying audio filter

### ISSUE THREAD

**Issue by ltgustavsen** [Mattk70/Chirpity-Electron#173]
Hi,
I’m wondering if this might be a bug. After playing a sound for the first time and turning on the audio filter, the program automatically jumps on the timeline. This only happens the first time. I'm currently using version 2.4.6 and don’t recall it behaving like this in previous versions. I've attached an example for reference.  The video shows the timeline jumping from 5:04 to 5:24.

[121211.wav.zip](https://github.com/user-attachments/files/18084777/121211.wav.zip)

https://github.com/user-attachments/assets/0797ed3b-d9b6-4ab0-99af-852f3f10297a

**Comment by Mattk70** [comment]
Hi @ltgustavsen, yes this is a bug. It's been around for a very long time! As you have reported it, I took the time to dig into why it happens. When the file is played, as the play head gets halfway across the spec it calls for the next audio spec. The bug is that when this queued audio spec arrives, it sets the start time for the current window to that of the next window. 

So it doesn't just skip forward to the next window the first time, it happens whenever you click on a result, play that result, and then toggle the audio filters. It's simple to fix, and I'll add it to the next release. Thanks for reminding me!
