### ISSUE TITLE
Not working on Parallels (Mac)

### ISSUE THREAD

**Issue by Vollpflock** [Mattk70/Chirpity-Electron#20]
Hi Matt

Thank you and @kahst so much for making this possible!

I installed Parallels on my Mac today and tried it out. It's functioning, but I'm unable to open sound files. This issue might be due to the TensorFlow.js Node module (@tensorflow/tfjs-node) or its native binding (tfjs_binding.node) causing problems.

A friend who uses Windows mentioned that it works fine for him.

Do you have plans to release a Mac version of the program soon, specifically once the BirdNET Analyzer is optimized for Mac? If not, I'm considering buying a Windows computer :)

**Comment by Mattk70** [comment]
HI @Vollpflock, I installed a trial version of parallels on my mac, and sure enough, it doesn;t work. The errors about tfjs_bindings are "file not found" errors. The files do exist in the locations referenced, so I can only presume that there is an issue with the Parallels Virtual Machine resolving the file paths. This is very far from my area of expertise! Maybe someone who's had some more experience with that issue can help. But, even when working, a Parallels installation is likely to be a lot slower than a native execution.

I can think of a couple of better options:

1. If you have an Intel Mac, you might consider Bootcamp, which allows you to dual boot into OSX/Windows. This should work, but I don't have access to an Intel Mac and can't test that.
2. If not, and you feel confident to do it, it's not that difficult to run the node app from an IDE like VS Code or Pycharm if you clone the repo. I could expand the README to go into more detail about how to do that.

In theory, it should be strightforwrd to release a native OSX version. That is one of the virtues of Electron development. However, I haven't begun to look at what's involved in the packaging stage and I believe this will involve shelling out more than the cost of a coffee to sign the package. Again, if anyone knows of a free way to release an App for a Mac, I'm all ears.

**Comment by Vollpflock** [comment]
Wow, I'm impressed that you went through the trouble of installing Parallels.

Sorry, I'm not familiar with Windows at all. I only have a silicon Mac (and an intel mac as well, but that’s not my main device).

To be honest, running the node app from an IDE like VS Code or PyCharm after cloning the repo seems like too much hassle for me. Also, I completely understand your reluctance to develop a dedicated Mac version.

Additionally, I tried using an old Windows laptop that belonges to my mother, but like on the Mac, I couldn't get the audio file import to work.

**I'm considering buying a Windows laptop specifically for Chirpity. Do you know what the system and hardware requirements are?**

It seems I need TensorFlow 2.5 or later, if I'm not mistaken. Does that mean I should follow these system and hardware requirements? https://www.tensorflow.org/install/pip 

Or maybe you could even recommend an (older) laptop? I know MacBooks in and out, but I'm not sure what to look for in a Windows laptop.

**Comment by Mattk70** [comment]
@Vollpflock - I may have a solution for a native Mac build. I say *may* because my only way to test this is to see if it works for me. Which it does.

First things first:
1. The installer is built for Apple silicon (**not Intel Macs**). I have installed it on an M2 macbook running Sanoma 14.0
2. It is not signed, so there are some addditional steps needed over a standard installation, I'll walk through these here.

### Installation
Please follow carefully!

I have uploaded a pkg file to the chirpity web server, it's not linked from the homepage, but you can download the file directly from this link:

https://chirpity.mattkirkland.co.uk/chirpity-0.11.0-arm64.pkg

Here are instructions to install the application: 

1. Find the file in your Downloads folder. 
2. **Important**: Hold down the 'control ^' button before clicking on the file. It should bring up a menu. Select the top link "Open"
3. You will see a warning like this:

<img width="328" alt="Screenshot 2024-01-28 at 10 35 06" src="https://github.com/Mattk70/Chirpity-Electron/assets/61826357/af9ab2a4-5327-4072-9411-c0bcfff79f36">

If you feel bold enough, hit open.
5. The installer window should appear.
6. In the first step of the installer, I'd recommend choosing "Install for me only" because when I tried this using the default "Install for all users of this computer" it installed, but didn't appear in the Applications folder. I had to hunt around for it. By choosing "Install for me only" the link appears in Home/Applications 

Let me know how you get on, if this works, I'll update the website with Mac and Wondows install options, which would be cool!

**Comment by Vollpflock** [comment]
Ddduuude that just worked on my M1 - you are awesome!

**Comment by Mattk70** [comment]
I'm glad to have helped, and glad there is a version working on for Mac! The website now has both installers available...
