### ISSUE TITLE
Queries about the Apple Silicon Version (first look)

### ISSUE THREAD

**Issue by Vollpflock** [Mattk70/Chirpity-Electron#22]
1. Experimental features are not working, except high-pass filter.
2. GPU not working.

**Comment by Mattk70** [comment]
HI @Vollpflock, thanks for the feedback!

It may be that you haven't enabled the experimental filters? Once you choose these parameters in the settings menu, you need to click on the icon in the filter panel. If it's enabled it will be yellow. The idea here is that you choose the settings, then toggle them on and off thorugh the panel.

When you say GPU 'not working', what do you mean? It's probably worth mentioning that the Mac M2 integrated GPU is *much* slower than the CPU backend, that's just the way it is. I'd imagine the GPU backend on an M1 is *reeeellly* slow. If your expeience is the analysis menu sticks on the message "model warming up" , it could be that it just takes forever to run the warm up session. So, without a doubt, you don't wan't to be using the GPU backend on an M series laptop or any Mac that uess the on-chip graphics. 

If you have a Mac Desktop *and* a separate graphics card - especially one from NVIDIA or AMD, I'd really love to get more feedback about that!

**Comment by Vollpflock** [comment]
Thanks for your effort!

Experimental features: Strange, now it’s working. I could swear that I clicked the icon in the filter panel and only high-pass filter was working. Definitely a mistake on my part. However, Context mode still won’t toggle on and SNR-filter stays non-responsive (at 0). 
![Screenshot 2024-01-28 at 21 16 30](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/19b67bb3-d6e8-42ea-add8-8097a3fa3c47)

Btw, I just watched your intro video where you apple noise reduction before analysis and get better results with the spotted crake. That’s interesting, I always thought that noise-reduction had to be applied after analysis for better results. 

GPU: You’re correct. Well, that was stupid. I have an old macbook with NVIDIA graphics and tried it, however it wasn’t working because it’s intel-based.

**Comment by Vollpflock** [comment]
And why won't context mode toggle on? Because I have birdnet enabled. So stupid, I need to go to bed.

**Comment by Mattk70** [comment]
@Vollpflock - you would have to jump straight into the experimental features, wouldn't you (hahaha)

Context mode:
1. Works by sliding the three-second analysis windows in a batch, so if the batch size is 1, it's disabled.
2. Is mutually exclusive with SNR: if you have one enabled, the other is disabled
3. Is about 40% slower and has a minimal impact on false positives - in my experience. I may ditch it.

Honestly, whilst getting the hang of Chirpity I'd steer clear of the experimental features. Adjusting these values wildly will have a dramatic - and usually negative - effect on the models' accuracy. This is because they modify the audio sent to the model. I will use them if I have a detection I hear, but the model doesn't pick it up. This can happen where there is particularly loud envronmental noise (like a passing car, or strong gust of wind). So I'd only use them to look at a particular call, by selecting / isolating it in the spectrogram and analysing just that small snippet of audio.

I just posted a discussion piece on performance, it shows just how poor the M2 GPU is for this kind of task...
