### ISSUE TITLE
Option to create a custom species list.

### ISSUE THREAD

**Issue by Vollpflock** [Mattk70/Chirpity-Electron#26]
Initial question: 3. Option to create a custom species list.

Your answer:
I get this is a feature in BirdNET, but I'm not convinced this is the best approach. What exactly are you looking to acheive?

More detailed:
This might just be a bad habit from my experience with Birdnet-Analyzer.

Main concern: I don’t fully understand on how the threshold for local birds is determined. Sure, I know, based on eBird data an so on. But I don’t fully trust it yet. My goal is sometimes to identify rare birds. I worry that rarities might not be recognized, so a custom species list would allow me to bypass the 'local birds' setting.

Minor: I want to filter out specific bird species that clutter my observations.  Additionally, a very low threshold often shows species that are highly unlikely to appear here, even as rarities. A post-analysis filter would suffice.

**Comment by Mattk70** [comment]
So - great, I get this, and it's as I thought :) 

Just to point out this: Chirpity has, even if I say so myself, a rather fancy feature under the help: "What species are detected?" It will explain how the list is affected by your settings. It then shows exactly what species are on the list with your current settings, and as an added bonus, a second list of all the species excluded. That should allow you to more effectively tune your settings, especially the species threshold for your location.

Doing this, I see also that the location filter makes some odd 'choices' for what might be seen locally. So I agree this can be improved. For want of a better way of putting it, I don't think getting people to enter a list of every species they want "on brand" for Chirpity, I'm looking for something more user-friendly. 

What I thought might work well, was to add the ability to drag a species from one list to the other, then, when you're done, you hit a button to save that selection as a custom list - and have the software manage list creation and storage. Since the location filter gets it mostly right, you'd only be tweaking a handful of species. That's my experience, anyway.

Still - this is just an early stage idea. It could change!

**Comment by Vollpflock** [comment]
> Just to point out this: Chirpity has, even if I say so myself, a rather fancy feature under the help: "What species are detected?" It will explain how the list is affected by your settings. It then shows exactly what species are on the list with your current settings, and as an added bonus, a second list of all the species excluded. That should allow you to more effectively tune your settings, especially the species threshold for your location.

This is great and may just what I need, haven't noticed it!

> What I thought might work well, was to add the ability to drag a species from one list to the other, then, when you're done, you hit a button to save that selection as a custom list - and have the software manage list creation and storage. Since the location filter gets it mostly right, you'd only be tweaking a handful of species. That's my experience, anyway.

Very interesting. You mean something like this (Birdnet-Pi)?
![Screenshot 2024-01-29 at 23 15 37](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/259f182d-ede6-45d2-adff-75bc988e4449)

**Comment by Mattk70** [comment]
Yep, that's the kind of thing, Not sure if BirdNET pi does this, but I'd hope to start with the location filtered list, so you don't have to build you custom list from scratch.

**Comment by Mattk70** [comment]
This has been added in v1.3.0

I decided against the appraoch of moving species between columns, as this is rather limiting, By allowing people to export the current list as a starting point, they can amend this for their custom list, This approach allows customisation of the species' common names too.
