### ISSUE TITLE
Amplification in post-analysis

### ISSUE THREAD

**Issue by Vollpflock** [Mattk70/Chirpity-Electron#28]
Initial question: 6. Amplification feature in experimental settings and maybe low-pass filter (because crickets)

Your answer: 
I am not sure what an amplificaiton filter means. Both models normalise any audio they receive (this effectively expands the dynamic range of the spectrograms, and helps with their performance) The spectrogram in the UI also normalises the audio - but what you hear is untampered with, unless you have an audio filter applied. Low pass filter - should be striaghtforward, I'll look into it for the next version.

More detailed:
I've previously discussed this with Frank. My recordings are quite soft because I use an electret microphone without an amplifier. I'd like to increase the volume post-analysis, so it's easier to hear and maybe even play through speakers.  And let's just say, I'd prefer not to jump out of my skin when I switch to full-volume YouTube right after these whisper-quiet recordings.

The screenshot below shows how quiet it is. In this case, it's manageable, but sometimes it's even quieter. I'm using .wav files for recording.
![Chirpity](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/46cc98c6-72e4-4ce2-bb9f-b733a2c897a6)

**Comment by Mattk70** [comment]
Ah, OK, makes sense. I'm using web audio for these audio filters, and there's a low pass (high cut) filter I was going to enable. There's also a gain node, which is what you're after here. Doing both isn't much more effort, but I need to think about which filter effects can be passed to the model. To paraphrase Roy Schneider, I'm going to need a bigger menu! That was on my list anyway, since the location map is too small.

**Comment by Vollpflock** [comment]
I think I was referring to normalizing the audio (post-analysis). I'd like all my sound files to be louder and maintain consistent audio levels when I'm reviewing them.

**Comment by Vollpflock** [comment]
Btw, how much amplification is applied to files pre-analysis at maximum for normalization? I suspect that identification might not be as accurate with very low volume files compared to those amplified beforehand, though I need to test this.

I have some extremely quiet files (-50db or so). I'm aware that normalization is ideally done during recording, but I recorded these in .wav format with an iPhone, which lacks a physical amplifier. There were instances of complete cutouts when it was windy, so I didn’t use gain control while recording and was hoping to normalize the audio in post.

**Comment by Mattk70** [comment]
If you amplify the sound, you'll be amplifying the noise too. It will sound louder, but the dynamic range will be the same. So, I'd say this idea is useful from the perspective of not blowing up your ears after cranking the volume on your computer while listening to the tracks, I very much doubt it will improve the accuracy of the models' predictions.

The normalisation for the models essentially scales the "volume" so that the quietest sound is silent and the loudest sound is the maximum volume the audio format can output. I've got "volume" in scare quotes because, in truth, the models don't listen to audio at all, they look at pictures. When I have a moment, I'll do a discussion post on this.

**Comment by Vollpflock** [comment]
Yes I know. I just wasn't sure if it would actually normalize or in other words amplify the signal that much, my files are just that quiet. 

I would highly appreciate the option for normalization and amplification after analysis so I wouldn't have to normalize the files beforehand.

**Comment by Vollpflock** [comment]
This is great, thank you! Will this be applied after analysis?

**Comment by Mattk70** [comment]
Yes, the gain level applied will be used in audio exports.

I did investigate normalisation. The algoithm is too complex for me to write from scratch using web audio. If I use ffmpeg, it's great. But really slow. Normalising took much longer then the analysis!  I may look into it further at some point to see if I can optimise it to work acceptably.
