### ISSUE TITLE
Dirunal mode

### ISSUE THREAD

**Issue by Vollpflock** [Mattk70/Chirpity-Electron#30]
Initial question: 8. Maybe an option to filter results after analysis? F.e. nocturnal and dirunal mode after analysis (before and after sunset/sunrise)? Or to search for certain species?

Your answer:

Nocmig mode and confidence threshold can be amended after analysis - select/click the appropriate button on the filter panel. To filter specific species - click that species' name in the summary. Click a filtered species again to 'unfilter' .

More detailed:
I didn't realize these settings are applied after analysis, that's great. How about a diurnal mode available, essentially the opposite of nocmig mode, listing the recordings from sunrise to sunset?

**Comment by Mattk70** [comment]
I should mention that if you have Nocmig mode on when you analyse a file / files, it won't look at the day time periods. This is intentional - for speed. On the other hand, if you forgot to put Nocmig mode on when you did the analysis, the filter is there to get rid of the dawn chorus etc. 

An inverse filter 'Daytime mode' isn't as straightforward as reversing a condition. I'm going to say right off I'm not inclined to do this. Give me a good case for it and I can have a better think about it.

**Comment by Vollpflock** [comment]
Ah, if it's complicated, then it's probably best to skip it. I can't think of an immediate use for it anyway. My original thought was to have a way to review all nocmig recordings first, and then all diurnal recordings, so as to avoid reviewing the same ones multiple times.
