### ISSUE TITLE
Export option for Manually Verified Detections

### ISSUE THREAD

**Issue by Vollpflock** [Mattk70/Chirpity-Electron#33]
**Is your feature request related to a problem? Please describe.**
The process of manually verifying recordings and then reporting birds is cumbersome and time-consuming. Typing in species name, number of individuals, date, time, and location for each manually verified observation is a daunting task.

**Describe the solution you'd like**
I'd like a feature to manually star identifications and an option to export these starred identifications. Then an option to export manually verified detections into a CSV file for importing into eBird (https://support.ebird.org/en/support/solutions/articles/48000907878-upload-spreadsheet-data-to-ebird#:~:text=Click%20the%20%22Submit%22%20tab%20on,Click%20%E2%80%9CImport%20File.%E2%80%9D). 

**Describe alternatives you've considered**
Manually report observations to eBird.

**Additional context**
This topic has come up several times in the BirdNET-Pi community, recently again, with discussions primarily focused on automated exports to eBird. However, an automated approach is not a good option, as many detections are false positives, and a detection doesn't automatically correspond to one individual. By enabling manual starring of each identification, users will not indiscriminately export all detections to eBird.

**Comment by Mattk70** [comment]
I can't offer exactly this, but I think Chirpity's  current capabilities may be a lot better than you realise. I've written a discussion topic on tidying up detections for export, take a look at  https://github.com/Mattk70/Chirpity-Electron/discussions/34.

There is also a process which will star records, and mark them as verified. You can manually create a record, or you can edit a record. Manual and edited records are starred, since the presumption is that you'll only create or edit a record where you're confident in the ID. That's not always true, you might edit a record to add a note that it's a possibility. Whilst it will still appear starred, and the hover link on the star will call it verified, there'll be a note against the record that you'll be able to refer back to.

The CSV is not specifically formatted for eBird. I *may* get around to this, but for now,  considering the multitude of submission services (BirdTrack and Trektellen in Europe, probably others) I figure a CSV you can wrangle is a good starting point. If you do it regularly, and have some Excel skillz, you should be able to automate a lot of the format conversion.

**Comment by Vollpflock** [comment]
Thank you for adding the extensive guide on your workflow in the "help" section.

I mistakenly moved files to another folder after analyzing them, which made me think there was a bug when I couldn't retrieve the results. Now the archive function is working great. This issue is minor, but it would be helpful if the system could still retrieve results even if the files are moved. Would that be possible or there a specific reason it's set up this way? 

Now I think I understand the archive function and it’s awesome, but I'm looking for a workflow where I can delete the original audio files and keep only the selected clips. For now I’m exporting as individual clips, but then I lose the location, confidence level, time, and spectrogram information, right? Or how do you manage your workflow? I assume you don't keep all the original audio files due to storage space.

**Comment by Vollpflock** [comment]
Thank you for explaining. I probably won't go back to reanalyze my files in the future, but that's a clever workaround. Could you tell me which file format you use for compression and how you go about compressing the files?

Also, are you concerned about the compression being too lossy, or do you keep the original clips of selected recordings just in case? If so, the file name will probably become more important for me again.

**Comment by kahst** [comment]
Yes, models are trained on rather messy audio data, and we add some impairments (like resampling artifacts) to the training samples during augmentation. So the models should be fairly robust against poor quality audio. However, better audio is always better and you'll also see some slight differences in scores if you change pre-processing parameters (e.g. resampling method). We use 48 kHz as sampling rate because the SWIFT units we mainly use for monitoring are set to 48 kHz, and thus it's just a convenient choice for us. Internally, BirdNET limits represented frequencies to 15 kHz (which is fine for birds).

**Comment by kahst** [comment]
> @kahst Does this mean that birdnet performs the same whether I use .wav and 20 kHz or 48 kHz for recording?

Kind of - BirdNET is used to resampling artifacts. However, if you pass the exact same soundscape at 48 kHz and 20 kHz through BirdNET, my bet is you will see some minor differences in scores. If you sample >=30kHz you shouldn't see a difference, since we cut off at 15 kHz internally.

**Comment by Vollpflock** [comment]
> > @kahst Does this mean that birdnet performs the same whether I use .wav and 20 kHz or 48 kHz for recording?
> 
> Kind of - BirdNET is used to resampling artifacts. However, if you pass the exact same soundscape at 48 kHz and 20 kHz through BirdNET, my bet is you will see some minor differences in scores. If you sample >=30kHz you shouldn't see a difference, since we cut off at 15 kHz internally.

Thanks, Stefan. I first thought I'd test this myself, but didn't have a chance. Just to be sure: Should I record at 30 kHz (and NOT 20 kHz), even if the bird sounds I'm recording only reach up to 10 kHz?
