### ISSUE TITLE
Explore Archive Menu disabled

### ISSUE THREAD

**Issue by Annerather** [Mattk70/Chirpity-Electron#38]
Since today in version 0.12.0 the "Explore Archive" menu is disabled. I was browsing the archive, found that the copyright notice at the bottom was on top of the last list entry. I thought restarting Chirpity would resolve this issue. Unfortunately after restarting Chirpity the menu item is disabled. I can still retrieve the results for a specific file, so the archive is there, but browsing the archive is impossible.

**Comment by Mattk70** [comment]
Hi @Annerather ,

I think this is a bug in 0.12.0 that is fixed in 0.12.1. I can't be entirely sure though. It's very likely the same bug if you find you can explore the archive after saving another record. 

To do a quick test, open a short file and analyse it. Hit Control-s to save the records.  If you do that and the 'explore archive' link is no longer greyed-out,  0.12.1 should fix your issue. This is a pre-release version, but you can download it here: https://github.com/Mattk70/Chirpity-Electron/releases/tag/v0.12.1 and you'll need to follow the same installation instrustions you did before, detailed on the website: https://chirpity.mattkirkland.co.uk

To tidy up  after your test records, go to 'Records > Remove current file from database' to remove the file and any records you just saved from the archive.

**Comment by Annerather** [comment]
Hi Matt, indeed that works as a workaround, so likely the bug you fixed. Thank you!

**Comment by Mattk70** [comment]
Great - I'll close this issue for now.
