### ISSUE TITLE
Sorting detections by confidence score does not work during analysis

### ISSUE THREAD

**Issue by DD4WH** [Mattk70/Chirpity-Electron#74]
During file processing of many hundred files (processing is ongoing and not yet finished):
* in the right bottom window (where the detections pop up), I press "Sort by confidence"
* after I do that, the detections are not sorted by confidence and the possiblity to press the sort button disappears. Instead "Start of civil twilight" appears as a text

Additionally:
* when I try to click on a species in the list on the bottom left to navigate to the species´ detections, the corresponding detections/files are not opened and the click is ignored by Chirpity

Maybe this is due to the ongoing file processing ?

**Comment by Mattk70** [comment]
Hi @DD4WH  So it does!

This is indeed due to the ongoing processing. It will sort itself out once the processing is complete.

While analysis is ongoing, any detections are appended directly to the table of results. At least, it will append them up to  a count of 500 detections. This tally of detections also controls whether the table header is rendered - as it only renders the header before the first detection. When you hit sort, the tally is not reset, so no header. 

While processing is ongoing, the species summary filter is not active. Again, this is because additional detections of any species will appear in the list of detections as soon as they are encountered.

So this is definitely a bug, the solution may be just to remove the sort icons (and click handler) until processing is complete, and similarly remove the click handler from the summary table, so species don't highlight when they aren't being filtered.

I will look at the alternative, which is to get all results from the database every time the model return some results, but I fear this will overwhelm the database process.

**Comment by Mattk70** [comment]
Fixed in https://github.com/Mattk70/Chirpity-Electron/discussions/77

I have removed the event handlers whilst analysis is ongoing. I did look at pulling results from the db as analysis was ongoing, however as I suspected, this soon overloaded the db process and the application ran very slowly.
