### ISSUE TITLE
First file works. Can't analyse second file.

### ISSUE THREAD

**Issue by DougWelch** [Mattk70/Chirpity-Electron#83]
**Describe the bug**
Working with 1.6.3 on Mac OS 14.4.1 (M1). Chirpity opens first file and analyses it as expected. After attempting to load a second file, all analyse options are greyed out.

**To Reproduce**
1. Go to 'File'
2. Click on 'Open Audio Files(s)'
3. Select file (a WAV file in case that matters). Spectrogram appears.
4. Go to 'Analysis'
5. Click on 'Analyse File'
6. Analysis happens as expected. Species counts and individual detections reported as expected.
7. Repeat 2) ands 3) for another file
8. Spectrogram of first file remains displayed, second file isn't loaded or displayed.

**Expected behavior**
I expected second file to load and have its spectrogram displayed and to have Analysis options available.

**Screenshots**
<img width="465" alt="Screenshot 2024-03-28 at 3 34 46 PM" src="https://github.com/Mattk70/Chirpity-Electron/assets/3171670/a17b8de3-73df-4ccf-8430-0f5ddc18248a">

**Additional context**
I'm a new user. Thanks for creating this impressive app

**Comment by Mattk70** [comment]
Hi @DougWelch , thanks for taking the time to let me know about this.

I've tried to recreate this error on the M2 I have for testing and can't - things are working at my end. However, I can see some log entries that give me a line to follow. I've created an updated installer based on my hunch - an attempt to address this issue here: https://github.com/Mattk70/Chirpity-Electron/releases/tag/v1.6.4

If you could give it a try (download/install this new pkg file), I'd appreciate it! Please let me know how you get on? I can't make any promises,  but fingers crossed!

**Comment by DougWelch** [comment]
Thank you for this quick attention! Unfortunately, no joy. Same behaviour.

**Comment by Mattk70** [comment]
Hmm. It's a tough one - mainly because I'm in the dark when I can't replicate the issue. I have one more idea I can try, I'll take a look at that tomorrow.

**Comment by DougWelch** [comment]
Thanks!!! Is there a design reason there isn't a Close File command?

**Comment by Mattk70** [comment]
OK - I have implemented the second idea I had. After this I'm out of ideas so if this doesn't work I'll need to reach out to the Node.js folks and report it as a possible bug in the underlying library I use. My latest effort is here:

https://github.com/Mattk70/Chirpity-Electron/releases/tag/v1.6.5

If you do still have issues, maybe share an example file? It's a long shot, but maybe the file itself is part of the issue.

As for Close File, I haven't really thought about it. When you open a new file or files, any existing open files are 'closed'. I have thought about the awkwardness of navigating between 'Records" > "Charts" / "Archive" and the current files you may be working on. But I haven't got around to dealing with that.

**Comment by DougWelch** [comment]
Same behaviour but this time a notification box appeared.
<img width="339" alt="Screenshot 2024-03-29 at 6 42 14 AM" src="https://github.com/Mattk70/Chirpity-Electron/assets/3171670/5468049e-4156-4f50-bf5d-ca980f47076e">

**Comment by Mattk70** [comment]
Hey - yes, this is the same issue as before. Does this happen with all files - did you try with an mp3, for example? Also, what happens if you try to analyse using the key shortcut cmd-A? The error you are getting is generated by the attempt to prepare the audio for the spectrogram in the UI, I'm curious to see if it affects getting the audio for analysis too. So far, you are the only person to have this issue. Not much consolation, I know, but it does make me wonder about the file you're analysing.

**Comment by DougWelch** [comment]
Here is a link to four of the files:[
](https://ln5.sync.com/dl/0ca678790/rzrpzb4r-r4rzh93p-ca9uaf6h-dry6iixz)

The WAV files are produced by AudioMoth units.

I will see if I can find some .mp3 files to try.

**Comment by Mattk70** [comment]
The files aren't attached. To attach wavs, you'll need to zip them. Just one will suffice, I am sure. Thanks!

**Comment by Mattk70** [comment]
One thing has occurred to me. What is the bitrate of your files?

**Comment by DougWelch** [comment]
48 kHz

**Comment by DougWelch** [comment]
wav.zip

**Comment by Mattk70** [comment]
Oh, ffs! It's because the WAV extension is uppercase.

**Comment by Mattk70** [comment]
Fixed in [1.6.6](https://github.com/Mattk70/Chirpity-Electron/releases/tag/v1.6.6)
