### ISSUE TITLE
Output stream error

### ISSUE THREAD

**Issue by JoostvanBruggen** [Mattk70/Chirpity-Electron#90]
Todat I got a bug: 

Output stream error: Cannot perform %TypedArray%.prototype.set on a detached ArrayBuffer.
What is this? Becasuse of this I can't play any found species-calls.

Joost van Bruggen

**Comment by Mattk70** [comment]
Hi @JoostvanBruggen, I'm not sure of the reason for this. This is an error that will appear if the file is not supported (see this issue: https://github.com/Mattk70/Chirpity-Electron/issues/85) , but it sounds like you have completed an analysis with the file, and are trying to play the detections. Could you describe the steps you have taken to elicit this error? Ideally, share a file where this happens so I can dig into what's happening? Thanks!

**Comment by JoostvanBruggen** [comment]
Might it be the problem that I gave the order to analyse a noctural recording in the evening, only to look at this the next morning. So in a way: could it be some sort of time-out-error?

**Comment by Mattk70** [comment]
There's no time out in the application code. Is it a possibility that your computer went to sleep / suspended during the analysis?

**Comment by Vollpflock** [comment]
Yeah I get the same error message. It happens when I search the archive and go through the detections quickly.
![Screenshot 2024-04-13 at 12 08 21](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/352124f1-3e8f-4f3b-88a9-f4799cfcf553)
![Screenshot 2024-04-13 at 12 09 16](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/d42f529f-ace5-45aa-b705-40fcc025a777)

**Comment by Mattk70** [comment]
Thanks @Vollpflock, that's helpful additional information. I'm still not sure what causes it though and can't make it happen on either of my machines. But, I have an idea.

The "Errror extracting audio segment" error is from ffmpeg, When you select a detection, ffmpeg is given the filename, and the detection's start and end point in the file. 

Since I can force the error to occur if I make the duration of requested audio very short e.g. 0.01 seconds, I am wondering if there could be a situation where the model was given a tiny fraction of audio (at the very end of a file), which it would pad out to 3 seconds with silence before attempting to predict the sound within it. It's also possible it may suggest Baumpieper for that audio segment (with not much confidence, hence the question mark on the label). If those things were to happen, I _think_ you would see the error you've captured here.

I'll dig a little bit more into this scenario, and if that is what's happening in this situation, I'll  prevent the model attempting predictions for very small snippets of audio.

**Comment by Mattk70** [comment]
Aha! I have found another scenario where this occurs. I analyse a file on my SD card, then start checking the results. Then I pull out the SD card, and continue checking the results. I get the error! Why ffmpeg  can't just error with "File not found" instead of something cryptic I don't know! Anyway, from the next release, Chirpity will let you know it can't find the file, if well, it can't find the file.

**Comment by Vollpflock** [comment]
Hm, I didn't pull out my external drive and it worked fine after quitting chirpity. Maybe I was scrolling through the detections too fast for my external drive to load?

**Comment by Mattk70** [comment]
Not sure. I'd expect that just to lead to laggy updates if it wasn't keeping up. But, maybe. If the file being inaccessible was the issue, the next version will at least be clear about this.
